name: Build Windows EXE

on:
  push:
    branches: [main]
  pull_request:
  release:
    types: [published]

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller TaskMover.spec

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: TaskMover-exe
          path: |
            dist/TaskMover.exe

      - name: Upload to GitHub Release (if release event)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/TaskMover.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}