name: TODO to Issue

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5.1.12
        with:
          LABEL: feature
          PROJECT: File Mover
          MILESTONE: MS.2
          # Optionally, to also match markdown checklists:
          CUSTOM_KEYWORDS: 'TODO,- [ ]'
