name: Markdown Checklist to Issue

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/Architechture/**.md'

jobs:
  checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run checklist extraction
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/checklist_to_issue.py
